version: "3.0"
services:
    dockerapp:
        image: danrojas7/dockerapp:latest
        ports:
            - "4000:5000"
        depends_on:
            - redis
        deploy:
            replicas: 2
    redis:
        image: redis:3.2.0
        deploy:
            replicas: 2
